pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
install:
  - ps: .\appveyor-set_version.ps1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(DOTNET_VERSION)'
  package_version: '$(DOTNET_VERSION)'
  assembly_version: '$(DOTNET_VERSION)'
  file_version: '$(DOTNET_VERSION)'
  informational_version: '{version}'
before_build:
  - cmd: >-
      dotnet restore

      cd KenticoInspector.Web\Client

      npm i

      npm run build
build:
  project: KInspector.sln
  verbosity: minimal
before_package:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - ps: .\appveyor-before_package.ps1
deploy:
  - provider: Environment
    name: Kentico Inspector Releases
    on:
      APPVEYOR_REPO_TAG: true
